-- ═══════════════════════════════════════════════════════════════════════════════
-- 🦀 RUST LSP CONFIGURATION
-- ═══════════════════════════════════════════════════════════════════════════════
-- Select which Rust LSP to use via Nix option (cb.neovim.rustLsp):
-- - "rust-analyzer": rustaceanvim with full feature set (linkedProjects, etc.)
-- - "rust-glancer":  native LSP config in rust_glancer.lua
--                     (experimental, no proc macros, no build.rs)
-- ═══════════════════════════════════════════════════════════════════════════════

-- lua/custom/rust_lsp_choice.lua is generated by home/neovim/default.nix.
local ok_choice, rust_lsp_choice = pcall(require, "custom.rust_lsp_choice")
local use_rust_glancer = ok_choice and rust_lsp_choice == "rust-glancer"

-- Additional Rust-specific settings (shared by both LSPs)
vim.api.nvim_create_autocmd("FileType", {
    pattern = "rust",
    callback = function()
        -- Show function signatures while typing
        vim.opt_local.signcolumn = "yes"
        -- Better completion experience
        vim.opt_local.completeopt = { 'menuone', 'noselect', 'noinsert' }
    end,
})

if use_rust_glancer then
    require("custom.plugins.rust_glancer")
    return
end

local rust_workspace = require("custom.plugins.rust_workspace")
rust_workspace.setup()

local rustaceanvim_config = {
    -- Plugin configuration
    tools = {
        hover_actions = {
            auto_focus = false,
        },
        float_win_config = {
            border = "rounded",
            focusable = true,
        },
    },
    -- LSP configuration
    server = {
        standalone = false,
        root_dir = function(file_name, default_root_dir)
            return rust_workspace.root_dir_for_file(file_name, default_root_dir)
        end,
        on_attach = function(client, bufnr)
            rust_workspace.detach_client_if_excluded(client, bufnr)
            -- All keybindings are centralized in keymaps.lua
        end,
        default_settings = {
            -- rust-analyzer language server configuration
            ['rust-analyzer'] = {
                -- Enable all the inlay hints
                inlayHints = {
                    bindingModeHints = {
                        enable = false,
                    },
                    chainingHints = {
                        enable = true,
                    },
                    closingBraceHints = {
                        enable = true,
                        minLines = 25,
                    },
                    closureReturnTypeHints = {
                        enable = 'never',
                    },
                    lifetimeElisionHints = {
                        enable = 'never',
                        useParameterNames = false,
                    },
                    maxLength = 25,
                    parameterHints = {
                        enable = true,
                    },
                    reborrowHints = {
                        enable = 'never',
                    },
                    renderColons = true,
                    typeHints = {
                        enable = true,
                        hideClosureInitialization = false,
                        hideNamedConstructor = false,
                    },
                },
                -- Lens settings for additional context
                lens = {
                    enable = true,
                    debug = {
                        enable = true,
                    },
                    implementations = {
                        enable = true,
                    },
                    run = {
                        enable = true,
                    },
                    methodReferences = {
                        enable = true,
                    },
                    references = {
                        adt = {
                            enable = true,
                        },
                        enumVariant = {
                            enable = true,
                        },
                        method = {
                            enable = true,
                        },
                        trait = {
                            enable = true,
                        },
                    },
                },
                -- Optimize check-on-save to reduce hanging issues
                checkOnSave = false,  -- Disabled by default to prevent hanging
                check = {
                    command = 'check',  -- Use 'check' instead of 'clippy' for speed
                    extraArgs = { '--message-format=json' },
                },
                -- Optimized cargo configuration to reduce load times
                cargo = {
                    allFeatures = false,  -- Disabled to reduce analysis time
                    loadOutDirsFromCheck = false,  -- Disabled to prevent hanging
                    runBuildScripts = false,  -- Disabled to prevent hanging on complex builds
                    noDefaultFeatures = false,
                },
                -- Optimize proc macros to reduce analysis overhead
                procMacro = {
                    enable = true,
                    attributes = {
                        enable = true,  -- Enable attribute macro expansion
                    },
                },
                -- Type information on hover
                hover = {
                    actions = {
                        enable = true,
                        implementations = {
                            enable = true,
                        },
                        references = {
                            enable = true,
                        },
                        run = {
                            enable = true,
                        },
                        debug = {
                            enable = true,
                        },
                    },
                },
                -- Completion settings
                completion = {
                    callable = {
                        snippets = 'fill_arguments',
                    },
                },
                -- Diagnostics
                diagnostics = {
                    enable = true,
                    experimental = {
                        enable = true,
                    },
                },
            },
        },
        settings = function(project_root, default_settings)
            return rust_workspace.apply_settings(project_root, default_settings)
        end,
    },
    -- DAP configuration for debugging
    dap = {
        adapter = {
            type = 'executable',
            command = 'lldb-vscode',
            name = 'rt_lldb',
        },
    },
}

vim.g.rustaceanvim = rustaceanvim_config

-- Note: LspInlayHint highlight is configured in colors.lua for consistency

-- Auto-format Rust files on save using rust-analyzer (rustfmt)
vim.api.nvim_create_autocmd("BufWritePre", {
    pattern = "*.rs",
    callback = function(args)
        local bufnr = args.buf
        -- Only format with rust-analyzer to ensure rustfmt is used
        local clients = vim.lsp.get_clients({ bufnr = bufnr })
        local has_ra = false
        for _, c in ipairs(clients) do
            if c.name == "rust_analyzer" or c.name == "rust-analyzer" then
                has_ra = c.supports_method("textDocument/formatting")
                break
            end
        end
        if has_ra then
            vim.lsp.buf.format({
                bufnr = bufnr,
                async = false,
                timeout_ms = 3000,
                filter = function(c)
                    return c.name == "rust_analyzer" or c.name == "rust-analyzer"
                end,
            })
        end
    end,
})
