local hyper = { 'option', 'command' }

hs.hotkey.bind(hyper, "b", function() hs.application.launchOrFocus("Dia") end)
hs.hotkey.bind(hyper, "t", function() hs.application.launchOrFocus("Ghostty") end)
hs.hotkey.bind(hyper, "f", function() hs.application.launchOrFocus("Figma") end)
hs.hotkey.bind(hyper, "e", function() hs.application.launchOrFocus("Signal") end)
hs.hotkey.bind(hyper, "s", function() hs.application.launchOrFocus("Spotify") end)
hs.hotkey.bind(hyper, "m", function() hs.application.launchOrFocus("Mail") end)
hs.hotkey.bind(hyper, "o", function() hs.application.launchOrFocus("Messages") end)
hs.hotkey.bind(hyper, "w", function() hs.application.launchOrFocus("WhatsApp") end)
hs.hotkey.bind(hyper, "g", function() hs.application.launchOrFocus("Discord") end)
hs.hotkey.bind(hyper, "c", function() hs.application.launchOrFocus("Zed") end)
hs.hotkey.bind(hyper, "x", function() hs.application.launchOrFocus("Xcode") end)
hs.hotkey.bind(hyper, "l", function() hs.application.launchOrFocus("Slack") end)
hs.hotkey.bind(hyper, "z", function() hs.application.launchOrFocus("zoom.us") end)
hs.hotkey.bind(hyper, "n", function() hs.application.launchOrFocus("Obsidian") end)
hs.hotkey.bind(hyper, "h", function() hs.application.launchOrFocus("IBKR Desktop") end)
hs.hotkey.bind(hyper, "v", function() hs.application.launchOrFocus("ProtonVPN") end)
